name: rte_rrtmgp_ci
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - urllib3
  - netcdf4
  - xarray
  - dask
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - colorcet
  - netcdf-fortran