name: Continuous Integration
on:
  push:
    branches:
    - main
    - develop
  pull_request:
    branches-ignore:
    - documentation
  workflow_dispatch:


jobs:
  CI:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        fpmodel: [DP, SP]
        toolchain:
          - {compiler: gcc, version: 10}
          - {compiler: gcc, version: 11}
          - {compiler: gcc, version: 12}
        include:
          - os: ubuntu-latest
            shell: bash -leo pipefail {0}
            use-cache: true
          - os: windows-latest
            shell: "msys2 -leo pipefail {0}"
            use-cache: false

    defaults:
      run:
        shell: ${{ matrix.shell }}

    env:
      # Core variables:
      FCFLAGS: "-ffree-line-length-none -m64 -std=f2008 -march=native -fbounds-check -fmodule-private -fimplicit-none -finit-real=nan -g -DRTE_USE_CBOOL -DRTE_USE_${{ matrix.fpmodel }}"
      # Make variables:
      RRTMGP_ROOT: ${{ github.workspace }}
      RRTMGP_DATA: ${{ github.workspace }}/rrtmgp-data
      RUN_CMD:
      FAILURE_THRESHOLD: 7.e-4
    steps:

    # Setup Fortran compiler
    - uses: fortran-lang/setup-fortran@v1.6.1
      id: setup-fortran
      with:
        compiler: ${{ matrix.toolchain.compiler }}
        version: ${{ matrix.toolchain.version }}

    - if: runner.os == 'Windows'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        path-type: inherit
        install: >-
          mingw-w64-x86_64-make
          mingw-w64-x86_64-netcdf-fortran

    - name: Debugging
      if: runner.os == 'Windows'
      run: |
        ls -1F /
        echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
        ls -1F /mingw64/bin
        echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
        ls -1F /c/ProgramData/chocolatey/bin
        echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
        find /c -name 'libgfortran*.dll'
        echo "=================================================="
        find /usr -name 'libgfortran*.dll'
        echo "=================================================="
        find /mingw64 -name 'libgfortran*.dll'

    # Relax failure thresholds for single precision
    #
    - name: Relax failure threshold for single precision
      if: matrix.fpmodel == 'SP'
      run: echo "FAILURE_THRESHOLD=3.5e-1" >> $GITHUB_ENV
    #
    # Check out repository under $GITHUB_WORKSPACE
    #
    - name: Check out code
      uses: actions/checkout@v4
    #
    # Check out data
    #
    - name: Check out data
      uses: actions/checkout@v4
      with:
        repository: earth-system-radiation/rrtmgp-data
        path: rrtmgp-data
        ref: v1.8.1
    #
    # Cache Conda packages
    #
    - name: Cache Conda packages
      uses: actions/cache@v4
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ hashFiles('environment-ci.yml') }}
    #
    # Set up Conda
    #
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        activate-environment: rte_rrtmgp_ci
        environment-file: environment-ci.yml
        auto-activate-base: false
        use-mamba: true
        # Use the cache properly:
        use-only-tar-bz2: true

    - name: Install NETCDF-Fortran
      if: runner.os == 'Linux'
      run: conda install -y -c conda-forge netcdf-fortran

    # Setup env variables if Linux and if Windows
    - name: Setup env variables - Linux
      if: runner.os == 'Linux'
      run: |
        echo "@@@@@@@@@@@@@@@@@@" $0
        echo FCINCLUDE=-I ${CONDA_PREFIX}/include >> $GITHUB_ENV
        echo LDFLAGS=-L ${CONDA_PREFIX}/lib >> $GITHUB_ENV
        echo LD_LIBRARY_PATH=${CONDA_PREFIX}/lib:${LD_LIBRARY_PATH} >> $GITHUB_ENV

    - name: Setup env variables - Windows
      if: runner.os == 'Windows'
      run: |
        echo "@@@@@@@@@@@@@@@@@@" $0
        echo FCINCLUDE="-I/mingw64/include" >> $GITHUB_ENV
        echo LDFLAGS="-L/mingw64/lib" >> $GITHUB_ENV
        echo LD_LIBRARY_PATH="/mingw64/lib:${LD_LIBRARY_PATH}" >> $GITHUB_ENV
        echo PATH="/mingw64/bin:${PATH}" >> $GITHUB_ENV
    #
    # Build libraries, examples and tests
    #
    - name: Build libraries
      run: |
        $FC --version
        make -j4 libs
    #
    # Run examples and tests
    #
    - name: Build and run examples and tests
      run: |
        make -j4 tests
    #
    # Compare the results
    #
    - name: Compare the results
      run: |
        make -j4 check
