name: Windows Workflow

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set environment variables
      run: |
        echo MY_VARIABLE=my_value >> $env:GITHUB_ENV
        echo ANOTHER_VARIABLE=another_value >> $env:GITHUB_ENV
      shell: pwsh

    - name: Print environment variables
      run: |
        echo $env:MY_VARIABLE
        echo $env:ANOTHER_VARIABLE
      shell: pwsh
